name: Validar proyecto
on:
  push:
  pull_request:
jobs:
  validar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Validar sintaxis Python
        run: python -m py_compile precios.py
        